### ISSUE TITLE
Plans for RxJS v8 and Observable spec (roadmap question)

### ISSUE THREAD

**Issue by kosich** [cartant/rxjs-etc#72]
Hi, Nicholas!

First of all: great library and thank you for your work on rxjs!

Do you plan to merge (or maybe partially merge) operators from this library into rxjs v8 or higher?  
Also, any thoughs/roadmap regarding upcoming yet-fuzzy Observable spec?

Thanks

**Comment by cartant** [comment]
> Do you plan to merge (or maybe partially merge) operators from this library into rxjs v8 or higher?

Not really. Something like `splitBy` should be added to RxJS - as `partition` is not especially useful - but there are no plans to add others. There was some discussion about including this package once the RxJS is reorganized to be a mono repo, but the outcome, IIRC, was that it would be better to not include it, as doing so would just introduce another bunch of official operators. I think it's better that it stays where it is. (The monorepo reorganization is so that the TSLint/ESLint rules can be made official.) Basically, the desire is for the core to be kept small - there are already so many operators in it - with userland operators being the norm. I guess this package shows how it's possible to write, test and distrubute userland operators.

> Also, any thoughs/roadmap regarding upcoming yet-fuzzy Observable spec?

Not sure what you mean by this. There is a general, non-language-specific [Observable Contract](http://reactivex.io/documentation/contract.html) - that all ReactiveX implementations should fulfill. If you are referring to the TC39 observable proposal, I am not optimistic regarding it's chances - it's stalled and for some insight into why, see [this comment](https://github.com/whatwg/dom/issues/544#issuecomment-351607779). However, there is some renewed discussion [here](https://github.com/tc39/proposal-observable/issues/201).

**Comment by kosich** [comment]
Thank you for the clarification and links!

(reversed order)

> Also, any thoughs/roadmap regarding upcoming yet-fuzzy Observable spec?

Sorry, yes, I meant the TC39 proposal. I've seen the renewed one, though missed the older thread. And yep, it seems like the new one got stuck as well. I guess I had an overly optimistic vision of that proposal...

> Do you plan to merge (or maybe partially merge) operators from this library into `rxjs` v8 or higher?

With the abovesaid, I hoped that `rxjs` v8+ would aim at covering generators/operators, while the core of the Observables would be implemented natively.

That would've relieved the pressure of implementing/supporting observable-core in `rxjs`.
That would've let authors provide and standardize more operators.
That would've let you merge this wonderful library with existing `rxjs` operators.

_( a chain of wishful thinking 👆)_

Currently, I'm working on a tool that has `rxjs` as a peer dependency. And I find this library to have lots of useful operators, while I'm a bit hesitant to add another peer dependency. So I hoped having one big vocabulary of operators would benefit the community.

_(marking this as detached from reality and closing)_

**Comment by cartant** [comment]
Note that you can always copy an operator to use in your own code and add the licence, etc. The reality is that most of the operators in the package are comparatively simple, tested and are highly unlikely to change.
